default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: "<%= ENV.fetch('DB_HOST', 'localhost') %>"
  port: "<%= ENV.fetch('DB_PORT', '5432') %>"
  username: "<%= ENV.fetch('DB_USER', 'postgres') %>"
  password: "<%= ENV.fetch('DB_PASS', 'postgres') %>"
  gssencmode: disable
  connect_timeout: 5
  checkout_timeout: 5
  reaping_frequency: 10

development:
  primary:
    <<: *default
    database: "<%= ENV.fetch('DB_NAME', 'fibe_rails') %>_development"

test:
  primary:
    <<: *default
    database: "<%= ENV.fetch('DB_NAME', 'fibe_rails') %>_test<%= ENV['TEST_ENV_NUMBER'] %>"

production:
  primary:
    <<: *default
    database: "<%= ENV.fetch('DB_NAME', 'fibe_rails') %>_production"
